language: java
sudo: required
jdk:
  - oraclejdk8
addons: # get google-chrome-stable
  chrome: stable
install: # Install ChromeDriver (64bits; replace 64 with 32 for 32bits).
  - wget -N http://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver 
script:
  - whereis google-chrome-stable
  - whereis chromedriver
  - "mvn clean verify"
  
jobs:
  include:
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: d13e551925de35534d50d3659dd52e430f0b057d
        skip_cleanup: true
        on:
          tags: false

