language: java
sudo: required
jdk:
  - oraclejdk8
  addons:
  chrome: stable
before_verify:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script: "mvn clean verify"